services:
  mongo-product:
    image: mongo:latest
    container_name: mongo-product
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: ecommerce_product_db
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata-product:/data/db
    networks:
      - ecomm-network

  postgres-order:
    image: postgres:18
    container_name: postgres-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_order_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata-order:/var/lib/postgresql
    networks:
      - ecomm-network

  mongo-user:
    image: mongo:latest
    container_name: mongo-user
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: ecommerce_user_db
    ports:
      - "27018:27017"
    volumes:
      - mongodbdata-user:/data/db
    networks:
      - ecomm-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - ecomm-network

volumes:
  mongodbdata-product:
  pgdata-order:
  mongodbdata-user:
  redisdata:

networks:
  ecomm-network: