spring:
  application:
    name: product-service
  data:
    mongodb:
#      uri: mongodb://mongo:mongo@localhost:27017/ecommerce_product_db?authSource=admin
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      database: ecommerce_product_db
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 200ms

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
