package com.niladri.common.dtos;

public enum EventType {
    PRODUCT_CREATED,
    ORDER_CREATED,
    INVENTORY_RESERVED,
    INVENTORY_RELEASED,
    INVENTORY_UNAVAILABLE,
    PAYMENT_PROCESSED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED
}
